import type { Metadata, Viewport } from "next";
import { Newsreader, Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from "@/components/Analytics";
import { Analytics as VercelAnalytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { FAQ } from "@/lib/faq";

// Display — an editorial serif with optical sizing; carries the authoritative,
// trusted-publication feel and elegant lining numerals.
const newsreader = Newsreader({
  subsets: ["latin"],
  variable: "--font-display",
  axes: ["opsz"],
  style: ["normal", "italic"],
  display: "swap",
  // Next has no built-in metrics for Newsreader, so skip its automatic
  // size-adjusted fallback (which logs a warning) and give it an explicit
  // serif fallback instead.
  fallback: ["Georgia", "Times New Roman", "serif"],
  adjustFontFallback: false,
});

// UI / body — a neutral, highly legible grotesk with tabular-number support.
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

import { SITE_URL, SITE_NAME, CONTENT_UPDATED } from "@/lib/site";
// Default import: named imports from JSON modules are being removed.
import pkg from "../package.json";

const TITLE = "ayakor — Bangladesh Income Tax & TDS Calculator";
const DESCRIPTION =
  "A precise, modern Bangladesh income-tax and TDS calculator for salaried individuals. Built on the Income Tax Act 2023 as amended by the Finance Act 2026 — covering Assessment Years 2025–26 and 2026–27, with every taxpayer category, investment rebate, minimum tax, and net-wealth surcharge. Free, open, and fully client-side.";

export const metadata: Metadata = {
  title: {
    default: `${TITLE} · AY 2026–27`,
    template: "%s · ayakor",
  },
  description: DESCRIPTION,
  applicationName: SITE_NAME,
  authors: [
    {
      name: "Md Rasel Ahmed",
      url: "https://www.linkedin.com/in/meetraselahmed/",
    },
  ],
  creator: "Md Rasel Ahmed",
  publisher: "ayakor",
  generator: "Next.js",
  category: "finance",
  classification: "Finance · Tax Calculator",
  keywords: [
    "ayakor",
    "Bangladesh income tax calculator",
    "Bangladesh TDS calculator",
    "BD tax calculator",
    "salary tax Bangladesh",
    "income tax calculator 2025-26",
    "income tax calculator 2026-27",
    "AY 2026-27",
    "AY 2025-26",
    "Assessment Year 2026-27",
    "ITA 2023",
    "Income Tax Act 2023",
    "Finance Act 2026",
    "Finance Ordinance 2025",
    "Finance Act 2024",
    "NBR",
    "National Board of Revenue",
    // Bengali equivalents — the interface is English, but the audience names
    // the thing in Bengali when searching.
    "আয়কর ক্যালকুলেটর",
    "বাংলাদেশ আয়কর ক্যালকুলেটর",
    "আয়কর হিসাব",
    "কর হিসাব বাংলাদেশ",
    "টিডিএস ক্যালকুলেটর",
    "আয়কর রিটার্ন",
    "investment rebate Bangladesh",
    "minimum tax Bangladesh",
    "net wealth surcharge calculator",
  ],
  metadataBase: new URL(SITE_URL),
  alternates: {
    canonical: "/",
    // The content is English but written for Bangladesh. `en-BD` is the honest
    // signal; the previous `en-US` told search engines to prefer this page for
    // American readers, which is the opposite of the audience.
    languages: {
      "en-BD": "/",
      en: "/",
      "x-default": "/",
    },
  },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: `${TITLE} · AY 2026–27`,
    description:
      "The precise, modern way to calculate your Bangladesh income tax and monthly TDS. Built on ITA 2023 and the Finance Act 2026 — free, open, and client-side.",
    locale: "en_BD",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "ayakor — Bangladesh Income Tax Calculator",
        type: "image/png",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: `${TITLE} · AY 2026–27`,
    description:
      "A precise, modern income-tax and TDS calculator for Bangladesh. Built on ITA 2023 and the Finance Act 2026.",
    images: ["/opengraph-image"],
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
    ],
    shortcut: "/icon.svg",
    // Generated by app/apple-icon.tsx — iOS won't render an SVG here.
    apple: [{ url: "/apple-icon", sizes: "180x180", type: "image/png" }],
  },
  referrer: "origin-when-cross-origin",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f6f2ea" },
    { media: "(prefers-color-scheme: dark)", color: "#141310" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  viewportFit: "cover",
};

// ───────────────────────────────────────────────────────────────────────────
// Structured data — emitted as a single @graph so the nodes reference each
// other by @id instead of floating as unrelated islands. That linkage is what
// lets a search engine treat "ayakor", its author and its FAQ as one entity
// rather than three coincidental blobs on a page.
// ───────────────────────────────────────────────────────────────────────────

const AUTHOR_ID = `${SITE_URL}/#author`;
const SITE_ID = `${SITE_URL}/#website`;
const APP_ID = `${SITE_URL}/#calculator`;

const author = {
  "@type": "Person",
  "@id": AUTHOR_ID,
  name: "Md Rasel Ahmed",
  email: "meetRaselAhmed@gmail.com",
  url: "https://www.linkedin.com/in/meetraselahmed/",
  // Profiles a search engine can reconcile into one person. Authorship signals
  // carry weight on financial content, where "who wrote this" is part of
  // whether it should be trusted.
  sameAs: [
    "https://www.linkedin.com/in/meetraselahmed/",
    "https://github.com/meetRaselAhmed",
  ],
};

const website = {
  "@type": "WebSite",
  "@id": SITE_ID,
  name: SITE_NAME,
  url: SITE_URL,
  description: DESCRIPTION,
  inLanguage: "en-BD",
  publisher: { "@id": AUTHOR_ID },
};

const webApplication = {
  "@type": ["WebApplication", "SoftwareApplication"],
  "@id": APP_ID,
  name: "ayakor",
  // Bengali variants are how most of the audience actually names this thing.
  // The interface is English, so these are entity aliases, not a claim of
  // Bengali content — no hreflang or translated page is implied.
  alternateName: [
    "Ayakor Bangladesh Tax Calculator",
    "আয়কর ক্যালকুলেটর",
    "বাংলাদেশ আয়কর ক্যালকুলেটর",
    "টিডিএস ক্যালকুলেটর",
  ],
  url: SITE_URL,
  description: DESCRIPTION,
  applicationCategory: "FinanceApplication",
  applicationSubCategory: "Tax Calculator",
  operatingSystem: "Any",
  browserRequirements: "Requires JavaScript. Requires HTML5.",
  inLanguage: "en-BD",
  isAccessibleForFree: true,
  isFamilyFriendly: true,
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "BDT",
  },
  author: { "@id": AUTHOR_ID },
  publisher: { "@id": AUTHOR_ID },
  isPartOf: { "@id": SITE_ID },
  license: "https://opensource.org/licenses/MIT",
  datePublished: "2025-07-01",
  // Freshness matters more than usual for tax content — both to searchers and
  // to assistants deciding whether a figure is still current.
  dateModified: CONTENT_UPDATED,
  softwareVersion: pkg.version,
  countriesSupported: "BD",
  about: [
    { "@type": "Thing", name: "Bangladesh Income Tax" },
    { "@type": "Thing", name: "Tax Deducted at Source (TDS)" },
    { "@type": "Thing", name: "Income Tax Act 2023" },
    { "@type": "Thing", name: "Finance Act 2026" },
  ],
  audience: {
    "@type": "Audience",
    audienceType: "Salaried individuals and taxpayers in Bangladesh",
    geographicArea: { "@type": "Country", name: "Bangladesh" },
  },
  potentialAction: {
    "@type": "UseAction",
    target: SITE_URL,
  },
};

// Mirrors the on-page FAQ so it stays eligible for rich results — Google
// requires the structured data to match visible text, so both read lib/faq.ts.
const faqPage = {
  "@type": "FAQPage",
  "@id": `${SITE_URL}/#faq`,
  isPartOf: { "@id": SITE_ID },
  inLanguage: "en-BD",
  mainEntity: FAQ.map((item) => ({
    "@type": "Question",
    name: item.q,
    acceptedAnswer: { "@type": "Answer", text: item.a },
  })),
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [author, website, webApplication, faqPage],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={[inter.variable, newsreader.variable].join(" ")}
    >
      <head>
        {/* Apply saved theme before paint to avoid a flash of the wrong theme */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('ayakor-theme');var d=t?t==='dark':window.matchMedia('(prefers-color-scheme: dark)').matches;if(d)document.documentElement.classList.add('dark');}catch(e){}})();`,
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            // `</script>` inside any FAQ answer would otherwise close this tag
            // and inject the rest as markup.
            __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c"),
          }}
        />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
      </head>
      <body className="font-body antialiased">
        {children}
        {/* Google Analytics 4 — gated on NEXT_PUBLIC_GA_ID */}
        <Analytics />
        {/* Vercel Web Analytics + Speed Insights — no-op unless deployed on Vercel */}
        <VercelAnalytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
